# Generated by Django 3.0.2 on 2020-03-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(verbose_name='date posted')),
                ('author', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(verbose_name='date posted')),
                ('author', models.CharField(max_length=32)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rychat.Thread')),
            ],
        ),
    ]
