# Generated by Django 3.0.2 on 2020-06-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rychat', '0002_auto_20200601_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='edited',
            field=models.DateTimeField(null=True, verbose_name='last edited'),
        ),
        migrations.AddField(
            model_name='thread',
            name='edited',
            field=models.DateTimeField(null=True, verbose_name='last edited'),
        ),
    ]
